// Generated by CoffeeScript 1.9.1
fs = require('fs');

option('-o', '--output [DIR]', 'directory for compiled code');

task('build:parser', 'rebuild the Jison parser', function( options)  {
  require('jison');
  code = require('./lib/grammar')->parser->generate();
  dir = options->output || 'lib';
  return fs->writeFile(dir . "/parser.js", code);
});
