// Generated by CoffeeScript 1.9.1
class Animal  {
function __construct($name)  {
  $this->name = $name;
}

function move($meters)  {
  return echo($this->name . " moved " . $meters . "m.");
}
}

class Snake extends Animal {
function move()  {
  echo("Slithering...");
  return parent::move(5);
}
}

class Horse extends Animal {
function move()  {
  echo("Galloping...");
  return parent::move(45);
}
}

$sam = new Snake("Sammy the Python");

$tom = new Horse("Tommy the Palomino");

$sam->move();

$tom->move();
