// Generated by CoffeeScript 1.9.1
if ($singing) {
  $mood = $greatlyImproved;
}

$mood = $singing ? $greatlyImproved : null;

if ($happy && $knowsIt) {
  $clapsHands();
  $chaChaCha();
} else {
  $showIt();
}

$date = $friday ? $sue : ($jill);
