// Generated by CoffeeScript 1.9.1
class Person  {
(function( options)  {
  return $this->name = options['name']; $this->age = options['age']; $this->height = options['height']; options;
});
}

tim = new Person([
  'age' => 4
]);
