// Generated by CoffeeScript 1.9.1
class Person  {
function __construct($options)  {
  $this->name = $options['name']; $this->age = $options['age']; $this->height = $options['height']; return $options;
}
}

$tim = new Person([
  'age' => 4
]);
