// Generated by CoffeeScript 1.9.1
$fn = function($filename) use (&$compile,&$fs) {
  return $fs->readFile($filename, function($err, $contents) use (&$filename,&$compile) {
    return $compile($filename, $contents->toString());
  });
};
foreach ($list as $filename) {
  $fn($filename);
}
