// Generated by CoffeeScript 1.9.1
if (( isset( $mind )) && (!  isset( $world ))) {
  $solipsism = true;
}

$speed = 0;

if (!  isset( $speed )) {
  $speed = 15;
}

$footprints =  isset( $yeti ) ? $yeti : ("bear");
