// Generated by CoffeeScript 1.9.1
echo(call_user_func((function() use (&$nonexistent,&$undefined,&$error) {
  try {
    return $nonexistent / $undefined;
  } catch ($error) {
    return "And the error is ... " . $error;
  }
})));
