// Generated by CoffeeScript 1.9.1
$globals = array_slice( (call_user_func((function() use (&$window) {
  $results = [];
  foreach ($window as $name) {
    $results[] = $name;
  }
  return $results;
}))), 0, 10 );
