// Generated by CoffeeScript 1.9.1
$weatherReport = function($location)  {
  return [$location, 72, "Mostly Sunny"];
};

$ref = $weatherReport("Berkeley, CA"); $city = $ref[0]; $temp = $ref[1]; $forecast = $ref[2];
