// Generated by CoffeeScript 1.9.1
$yearsOld = [
  'max' => 10,
  'ida' => 9,
  'tim' => 11
];

$ages = call_user_func((function() use (&$yearsOld) {
  $results = [];
  foreach ($yearsOld as $child => $age) {
    $results[] = $child . " is " . $age;
  }
  return $results;
}));
