// Generated by CoffeeScript 1.9.1
futurists = [
  'sculptor' => "Umberto Boccioni",
  'painter' => "Vladimir Burliuk",
  'poet' => [
    'name' => "F.T. Marinetti",
    'address' => ["Via Roma 42R", "Bellagio, Italy 22021"]
  ]
];

$undefined = futurists['poet'];
