// Generated by CoffeeScript 1.9.1
$song = ["do", "re", "mi", "fa", "so"];

$singers = [
  'Jagger' => "Rock",
  'Elvis' => "Roll"
];

$singers_obj = (object) [
  'Jagger' => "Rock",
  'Elvis' => "Roll"
];

echo($singers_obj->Jagger);

$bitlist = [1, 0, 1, 0, 0, 1, 1, 1, 0];

$kids = [
  'brother' => [
    'name' => "Max",
    'age' => 11
  ],
  'sister' => [
    'name' => "Ida",
    'age' => 9
  ]
];
