// Generated by CoffeeScript 1.9.1
$snack = 'peanuts';

$drink = 'beer';

$this->seat = 'blanket';

$this->company = 'you';

$picnic = [
  'snack' => $snack,
  'seat' => $this->seat,
  '.drink' => $drink,
  '.company' => $this->company
];
