// Generated by CoffeeScript 1.9.1
$number = 42;

$opposite = true;

if ($opposite) {
  $number = -42;
}

$square = function($x)  {
  return $x * $x;
};

$list = [1, 2, 3, 4, 5];

$math_hash = [
  'root' => 'sqrt',
  'square' => $square,
  'cube' => function($x) use (&$square) {
    return $x * $square($x);
  }
];

$math = (object) [
  'root' => 'sqrt',
  'square' => $square,
  'cube' => function($x) use (&$square) {
    return $x * $square($x);
  }
];

$race = function()  {
  $__args = func_get_args();
  $winner = $__args[0]; $runners = array_slice($__args, 1);
  return var_dump($winner, $runners);
};

if ( isset( $elvis )) {
  echo("I knew it!");
}

$cubes = call_user_func((function() use (&$list,&$math) {
  $results = [];
  foreach ($list as $num) {
    $results[] = $math->cube($num);
  }
  return $results;
}));
