// Generated by CoffeeScript 1.9.1
$numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

$start = array_slice( $numbers, 0, 3 );

$middle = array_slice( $numbers, 3, -2 );

$end = array_slice( $numbers, -2 );

$copy = array_slice( $numbers, 0 );
