// Generated by CoffeeScript 1.9.1
$zip = isset( $lottery ) && is_callable( [$lottery, "drawWinner"] ) ?  isset( $lottery->drawWinner()->address->zipcode ) ? $lottery->drawWinner()->address->zipcode : null : null;
