// Generated by CoffeeScript 1.9.1
$winner = isset( $lottery ) && is_callable( [$lottery, "drawWinner"] ) ? $lottery->drawWinner() : null;

$zip =  isset( $winner->address->zipcode ) ? $winner->address->zipcode : null;
