// Generated by CoffeeScript 1.9.1
$gold = $silver = $rest = "unknown";

$awardMedals = function() use (&$gold,&$silver,&$rest) {
  $__args = func_get_args();
  $first = $__args[0]; $second = $__args[1]; $others = array_slice($__args, 2);
  $gold = $first;
  $silver = $second;
  return $rest = $others;
};

$contenders = ["Michael Phelps", "Liu Xiang", "Yao Ming", "Allyson Felix", "Shawn Johnson", "Roman Sebrle", "Guo Jingjing", "Tyson Gay", "Asafa Powell", "Usain Bolt"];

call_user_func_array($awardMedals, $contenders);

echo("Gold: " + $gold);

echo("Silver: " + $silver);

echo("The Field: " + $rest);
