// Generated by CoffeeScript 1.9.1
score = 76;

grade = call_user_func((function()  {
  switch (false) {
    case !(score < 60):
      return 'F';
    case !(score < 70):
      return 'D';
    case !(score < 80):
      return 'C';
    case !(score < 90):
      return 'B';
    default:
      return 'A';
  }
}));
